<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-MVV1HI5" failures="1" tests="3" name="Personal Loan" time="0.036" errors="0" timestamp="2023-03-11T23:54:51 TRT">
  <testcase classname="TestNG.Demo1_Test" name="demo" time="0.008">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at TestNG.Demo1_Test.demo(Demo1_Test.java:13)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1589)
... Removed 19 stack frames]]>
    </failure>
  </testcase> <!-- demo -->
  <testcase classname="TestNG.Demo1_Test" name="secondTest" time="0.001"/>
  <testcase classname="TestNG.Demo2_Test" name="thirdTest" time="0.0"/>
</testsuite> <!-- Personal Loan -->
